# Generated by Django 5.2.7 on 2025-10-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Principal', max_length=100)),
                ('total_due', models.IntegerField(default=0)),
                ('installment_due', models.IntegerField(default=0)),
                ('cutoff_day', models.IntegerField(default=20)),
                ('payment_day', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_min_spend', models.IntegerField(default=600)),
                ('bus_monthly', models.IntegerField(default=100000)),
                ('last_bus_topup', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense')], max_length=3)),
                ('amount', models.IntegerField()),
                ('when', models.DateField()),
                ('category', models.CharField(default='general', max_length=60)),
                ('note', models.TextField(blank=True, default='')),
            ],
        ),
    ]
